enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[Instagram]
apkmirror-dlurl = "https://apkmirror.com/apk/instagram/"
included-patches = "'Hide ads' 'Disable signature check'"
exclusive-patches = true

[Music]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"

[Twitter]
apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter/"

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"

[Duolingo]
apkmirror-dlurl = "https://www.apkmirror.com/apk/duolingo/"
included-patches = "'Disable ads'"
exclusive-patches = true

